#!/bin/zsh
set -e
cd "${0:A:h}"
BUFFER=""
DICTFILE="$(dirname $0)/../dicts/mozc.out.txt"
while true; do
	read -r -s -k 1 c
	if [ "$c" = "." ]; then
		echo -ne $BUFFER | xsel -i -b
		exit
	elif [ "$c" = "," ]; then
		BUFFER=${BUFFER%?}
	elif [ "$c" = "" ]; then
		exit
	elif [ "$c" = "1" ]; then
		DICTFILE="$(dirname $0)/../dicts/mozc.out.txt"
	elif [ "$c" = "2" ]; then
		DICTFILE="$(dirname $0)/../dicts/sunpinyin.out.txt"
	else
		BUFFER+="$(cat "$DICTFILE" | \
			fzf --algo=v1 --query=$c | \
			cut -d' ' -f2 )"
	fi
	echo "$BUFFER"
done
